// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXesaf2apZcdDSzlqqQ9Ycou1s1gKNpTo',
    appId: '1:776648753457:android:d22ede1c28e4aacb98f010',
    messagingSenderId: '776648753457',
    projectId: 'withcenter-test-3',
    databaseURL: 'https://withcenter-test-3-default-rtdb.firebaseio.com',
    storageBucket: 'withcenter-test-3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6oypaQkHZocWP6-tGCDvHAK5LziEQhMM',
    appId: '1:776648753457:ios:b6719dfc0ea5773198f010',
    messagingSenderId: '776648753457',
    projectId: 'withcenter-test-3',
    databaseURL: 'https://withcenter-test-3-default-rtdb.firebaseio.com',
    storageBucket: 'withcenter-test-3.appspot.com',
    androidClientId: '776648753457-2opu3g9o51193enkoek48fhpedgpmm1d.apps.googleusercontent.com',
    iosClientId: '776648753457-iavpuc8tp91um7n5d9vdj9bu2jqi1csu.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );
}
